### ISSUE TITLE
RE Feedback - level of abstraction of Client class

### ISSUE THREAD

**Issue by andynu** [em-jov/meteoalarm#2]
The client class seems to be doing two different kinds of things.
1. providing weather data
2. managing http requests and response code parsing.

Perhaps consider extracting your http parsing code into its own utility class separate from the main public API provided by the Client class.

Cheers

**Comment by em-jov** [comment]
@andynu Appreciate your feedback. Incorporated your suggestion, and adjusted the code accordingly. Thank you.
